# Generated by Django 4.1 on 2022-08-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_journals_posted_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Journals',
        ),
    ]
